### ISSUE TITLE
Can't get hardware video decoding acceleration working on Linux

### ISSUE THREAD

**Issue by ddellarocca** [marzeq/xbox-cloud-gaming-electron#2]
Hi,
I've downloaded the latest version but I'm not able to get hardware video acceleration working.
The specs of my system are:

- OS: Debian unstable
- DE: Gnome 43.1
- Graphic server: Wayland

When I run the wrapper vanilla i get:
```
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
(node:10916) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/tmp/.mount_xbox-crrrPb9/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:514:26)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `xbox-cloud-gaming-electron --trace-warnings ...` to show where the warning was created)
(node:10916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[10955:0110/104204.357313:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

If I set `export LIBVA_DRIVER_NAME=iHD` I no longer have the error `libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed` but still no hardware acceleration:
```
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
(node:11129) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/tmp/.mount_xbox-cxsCJt7/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:514:26)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `xbox-cloud-gaming-electron --trace-warnings ...` to show where the warning was created)
(node:11129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[11168:0110/104405.159984:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

I check if hardware acceleration is working with `sudo intel_gpu_top`, as you can see no app is using hardware video decoding:
![Screenshot from 2023-01-09 17-09-50](https://user-images.githubusercontent.com/29358615/211517394-b2b1a341-993f-4c43-8270-41a85132aae5.png)
If I play a YT video through FireFox I have video decoding workload:
![Screenshot from 2023-01-09 17-10-42](https://user-images.githubusercontent.com/29358615/211517625-206a8c1b-c5e3-4c47-b783-e875ec084b3b.png)

Can you help me out?

**Comment by marzeq** [comment]
Hey, I'm not very familiar with Debian, but I'll try to help. Have you
checked out this (https://wiki.debian.org/HardwareVideoAcceleration) wiki
page and followed the instructions for your graphics card? From my testing,
XCloud only works with VA-API, so maybe other forms of hardware accelerated
decoding work, but not VA.

**Comment by ddellarocca** [comment]
Yes, I already checked the docs since I have it working on FireFox with VA-API.
Do you have hardware video acceleration working? Have you checked with `intel_gpu_top` or other tools?

edit: running it with `--gpu-info` gives me:
![image](https://user-images.githubusercontent.com/29358615/211531777-3de8a33b-6039-4d59-8865-91359a51e89b.png)

It seems enabled but still no video decode workload is being produced.

**Comment by marzeq** [comment]
I think I might know what's the problem, and it has to do with my bad coding (lol). I suspect that the output of `vainfo` goes to stdout for some reason and so the app can't capture it and so it can't verify whether hardware accell is available or not, so it doesn't enable it. I'll try to verify my theory asap. In the meantime, can you tell me whether you get a warning telling you about hardware accell being disabled when you launch the app?

**Comment by ddellarocca** [comment]
Where should I check for that warning?

**Comment by marzeq** [comment]
It should be a red text warning on a white background in the app, above the UI.

**Comment by ddellarocca** [comment]
No warning present, I'm thinking that is a problem with Debian Unstable since I cannot get hardware video acceleration in also in chromium. It works only in firefox

**Comment by marzeq** [comment]
If you can't get it working in Chromium, you can't get it working here, sorry. Closing.

**Comment by marzeq** [comment]
I'll try and help you with enabling this for Chromium because that would fix it here too, but this has nothing to do with my code.

**Comment by marzeq** [comment]
@ddellarocca I know that you are using Debian, but I found the Arch wiki to be more helpful in this context. Please check out https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration and see if you've set everything up correctly. The launch flags should be handled already, so you don't have to worry about them.

**Comment by ddellarocca** [comment]
Hi @marzeq , thanks for the help, I've tried it many times but no luck.
Don't worry I'll figure it out myself when I have half a day free, thanks for the help anyway!
